spring:
   application:
      name: Gateway
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
         default-filters:
         - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
         globalcors:
            corsConfigurations:
               '[/**]':
                  allowedOrigins: '*'
                  allowedMethods: '*'
                  allowedHeaders: '*'
server:
   port: ${server-port:8080}
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8083/eureka
jwt:
   secret: ${jwtsecret:w2m_super_secret}