spring:
   application:
      name: Gateway
   cloud:
      gateway:
         discovery:
            locator:
               enabled: true
server:
   port: ${server-port:8080}
eureka:
   client:
      serviceUrl:
         defaultZone: http://localhost:8083/eureka
jwt:
   secret: ${jwtsecret:w2m_super_secret}