spring:
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  profiles:
    active: ${profile:local}
  application:
    name: Auth
  liquibase:
    change-log: classpath:db/liquibase-changelog.xml
    contexts: ${profile:local}
  jackson:
    time-zone: Europe/Madrid
    serialization:
      indent-output: true
      fail-on-empty-beans: false
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: true
  datasource:
    username: ${db-user:superheroes}
    password: ${db-password:superheroes}
    url: jdbc:h2:mem:superheroes
    jdbc-url: ${spring.datasource.url}
    platform: h2
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    properties:
      hibernate:
        "[format_sql]": true
        "[enable_lazy_load_no_trans]": false
  h2:
    console:
      enabled: true
      
server:
  port: ${server-port:8080}
  error:
    whitelabel:
      enabled: false

w2m:
  name: auth
  rest:
    url:
      prefix: /api/${w2m.name}
   
jwt:
  secret: ${jwtsecret:w2m_super_secret}

coreapp-ms-auth: http://${w2m-ms-auth-service-host:localhost}:${w2m-ms-auth-service-port:8080}    
coreapp-ms-auth-dns: http://w2m-ms-auth:8080    

---
spring:
  config:
    activate:
      on-profile: local
  output:
    ansi:
      enabled: always
  liquibase:
    enabled: true
  jpa:
    show-sql: false
    properties:
      hibernate:
        "[show_sql]": false
        "[format_sql]": true
        "[show_parameters]": true
        temp:
          "[use_jdbc_metadata_defaults]": false
          